#!/bin/sh

# Set the project root directory
PROJECT_ROOT="$(git rev-parse --show-toplevel)"

# Set the script file
SCRIPT="$PROJECT_ROOT/bin/screenplain-convert.sh"

# Check if the script exists
if [ ! -f "$SCRIPT" ]; then
    echo "Error: Script not found: $SCRIPT"
    exit 1
fi

# Get the list of changed fountain files
CHANGED_FOUNTAIN_FILES=$(git diff --cached --name-only --diff-filter=d | grep -E '^.*fountain/.*\.fountain$')

if [ -n "$CHANGED_FOUNTAIN_FILES" ]; then
    # Run the script for the changed fountain files
    echo "Updating PDFs for changed fountain files..."
    for s in $CHANGED_FOUNTAIN_FILES
    do
        rel_path="${s#*fountain/}"
        base_dir="$(dirname "$s")"
        pdf_dir="${base_dir/fountain/pdf}"
        pdf_path="$pdf_dir/$rel_path"
        # Run the script and store the output (1 if updated, 0 if not updated)
        UPDATED=$("$SCRIPT" "$PROJECT_ROOT/$s" "$PROJECT_ROOT/${pdf_path%.fountain}.pdf")

        if [ "$UPDATED" -eq 1 ]; then
            git add "$PROJECT_ROOT/${pdf_path%.fountain}.pdf"
        fi
    done
fi

